# Form implementation generated from reading ui file 'DialogContractExplorer.ui'
#
# Created by: PyQt6 UI code generator 6.3.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 500)
        Dialog.setMinimumSize(QtCore.QSize(200, 300))
        Dialog.setMaximumSize(QtCore.QSize(16777215, 16777215))
        Dialog.setSizeGripEnabled(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_close = QtWidgets.QPushButton(Dialog)
        self.pushButton_close.setAutoDefault(False)
        self.pushButton_close.setObjectName("pushButton_close")
        self.verticalLayout.addWidget(self.pushButton_close)
        self.comboBox_contracts = QtWidgets.QComboBox(Dialog)
        self.comboBox_contracts.setObjectName("comboBox_contracts")
        self.verticalLayout.addWidget(self.comboBox_contracts)
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_collapse = QtWidgets.QPushButton(self.widget)
        self.pushButton_collapse.setObjectName("pushButton_collapse")
        self.horizontalLayout.addWidget(self.pushButton_collapse)
        self.pushButton_expand = QtWidgets.QPushButton(self.widget)
        self.pushButton_expand.setAutoDefault(False)
        self.pushButton_expand.setObjectName("pushButton_expand")
        self.horizontalLayout.addWidget(self.pushButton_expand)
        self.verticalLayout.addWidget(self.widget)
        self.treeView_result = QtWidgets.QTreeView(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeView_result.sizePolicy().hasHeightForWidth())
        self.treeView_result.setSizePolicy(sizePolicy)
        self.treeView_result.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustIgnored)
        self.treeView_result.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectItems)
        self.treeView_result.setSortingEnabled(True)
        self.treeView_result.setAnimated(True)
        self.treeView_result.setExpandsOnDoubleClick(True)
        self.treeView_result.setObjectName("treeView_result")
        self.treeView_result.header().setVisible(True)
        self.verticalLayout.addWidget(self.treeView_result)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Contract Explorer"))
        self.pushButton_close.setText(_translate("Dialog", "Close"))
        self.pushButton_collapse.setText(_translate("Dialog", "Collapse All"))
        self.pushButton_expand.setText(_translate("Dialog", "Expand All"))
